import type { CanonicalJob } from '@german-smart-apply/shared';

/**
 * Seed data for the mock API layer. Modeled on plan.md's "small trusted
 * German source set" â€” a mix of high-trust ATS-sourced roles plus one
 * deliberately suspicious listing so the scam-risk / trust-signal UI has
 * something real to surface (never hide risk from the user).
 */
export const JOB_FIXTURES: CanonicalJob[] = [
  {
    jobId: 'job-01',
    sourceId: 'src-greenhouse-zalando',
    sourceType: 'greenhouse',
    sourceUrl: 'https://boards.greenhouse.io/zalando/jobs/1001',
    originalJobId: 'zalando-1001',
    companyNameRaw: 'Zalando SE',
    companyNameNormalized: 'Zalando',
    jobTitleRaw: 'Senior Backend Engineer (Java)',
    jobTitleNormalized: 'Senior Backend Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Own core checkout services used by millions of customers across Europe. Work with Java, Kotlin, and event-driven microservices. Collaborate with product and platform teams to scale reliably during peak sales.',
    language: 'en',
    locationRaw: 'Berlin, Germany',
    locationNormalized: 'Berlin',
    countryCode: 'DE',
    remoteType: 'hybrid',
    employmentType: 'full_time',
    seniority: 'senior',
    salaryMin: 75000,
    salaryMax: 95000,
    salaryCurrency: 'EUR',
    techStackTags: ['Java', 'Kotlin', 'Kafka', 'AWS', 'Microservices'],
    applyUrl: 'https://boards.greenhouse.io/zalando/jobs/1001/apply',
    postedAt: '2026-07-02T09:00:00.000Z',
    crawledAt: '2026-07-03T04:00:00.000Z',
    sourceTrustScore: 0.95,
    scamRiskScore: 0.03,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-02',
    sourceId: 'src-lever-n26',
    sourceType: 'lever',
    sourceUrl: 'https://jobs.lever.co/n26/1002',
    originalJobId: 'n26-1002',
    companyNameRaw: 'N26 GmbH',
    companyNameNormalized: 'N26',
    jobTitleRaw: 'Frontend Engineer - React',
    jobTitleNormalized: 'Frontend Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Build the customer-facing banking app used by millions of Europeans. Strong TypeScript and React skills required. Work closely with design and backend teams in an agile squad.',
    language: 'en',
    locationRaw: 'Berlin, Germany (Hybrid)',
    locationNormalized: 'Berlin',
    countryCode: 'DE',
    remoteType: 'hybrid',
    employmentType: 'full_time',
    seniority: 'mid',
    salaryMin: 62000,
    salaryMax: 78000,
    salaryCurrency: 'EUR',
    techStackTags: ['React', 'TypeScript', 'GraphQL', 'Jest'],
    applyUrl: 'https://jobs.lever.co/n26/1002/apply',
    postedAt: '2026-07-05T09:00:00.000Z',
    crawledAt: '2026-07-05T10:00:00.000Z',
    sourceTrustScore: 0.91,
    scamRiskScore: 0.05,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-03',
    sourceId: 'src-successfactors-sap',
    sourceType: 'successfactors',
    sourceUrl: 'https://jobs.sap.com/job/1003',
    originalJobId: 'sap-1003',
    companyNameRaw: 'SAP SE',
    companyNameNormalized: 'SAP',
    jobTitleRaw: 'Fullstack Software Engineer (m/w/d)',
    jobTitleNormalized: 'Fullstack Software Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Join a cloud platform team building enterprise SaaS products. Node.js backend, React frontend, PostgreSQL. Mentor junior engineers and contribute to architecture decisions.',
    language: 'de',
    locationRaw: 'Walldorf, Deutschland',
    locationNormalized: 'Walldorf',
    countryCode: 'DE',
    remoteType: 'onsite',
    employmentType: 'full_time',
    seniority: 'senior',
    salaryMin: 70000,
    salaryMax: 88000,
    salaryCurrency: 'EUR',
    techStackTags: ['Node.js', 'React', 'PostgreSQL', 'TypeScript'],
    applyUrl: 'https://jobs.sap.com/job/1003/apply',
    postedAt: '2026-06-28T09:00:00.000Z',
    crawledAt: '2026-06-29T06:00:00.000Z',
    sourceTrustScore: 0.93,
    scamRiskScore: 0.04,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-04',
    sourceId: 'src-greenhouse-delivery-hero',
    sourceType: 'greenhouse',
    sourceUrl: 'https://boards.greenhouse.io/deliveryhero/jobs/1004',
    originalJobId: 'dh-1004',
    companyNameRaw: 'Delivery Hero SE',
    companyNameNormalized: 'Delivery Hero',
    jobTitleRaw: 'DevOps Engineer',
    jobTitleNormalized: 'DevOps Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Operate Kubernetes clusters across multiple regions. Build CI/CD pipelines, observability, and cost-optimization tooling for a fast-moving logistics platform.',
    language: 'en',
    locationRaw: 'Remote (Germany)',
    locationNormalized: 'Remote - Germany',
    countryCode: 'DE',
    remoteType: 'remote',
    employmentType: 'full_time',
    seniority: 'mid',
    salaryMin: 65000,
    salaryMax: 80000,
    salaryCurrency: 'EUR',
    techStackTags: ['Kubernetes', 'Terraform', 'AWS', 'Docker', 'Go'],
    applyUrl: 'https://boards.greenhouse.io/deliveryhero/jobs/1004/apply',
    postedAt: '2026-07-06T09:00:00.000Z',
    crawledAt: '2026-07-06T12:00:00.000Z',
    sourceTrustScore: 0.85,
    scamRiskScore: 0.12,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-05',
    sourceId: 'src-ashby-trade-republic',
    sourceType: 'ashby',
    sourceUrl: 'https://jobs.ashbyhq.com/traderepublic/1005',
    originalJobId: 'tr-1005',
    companyNameRaw: 'Trade Republic Bank GmbH',
    companyNameNormalized: 'Trade Republic',
    jobTitleRaw: 'Data Scientist, Risk',
    jobTitleNormalized: 'Data Scientist',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Build fraud and credit risk models for a fast-growing broker. Python, SQL, and ML pipeline experience required. Work directly with compliance and engineering.',
    language: 'en',
    locationRaw: 'Berlin, Germany',
    locationNormalized: 'Berlin',
    countryCode: 'DE',
    remoteType: 'hybrid',
    employmentType: 'full_time',
    seniority: 'mid',
    salaryMin: 68000,
    salaryMax: 85000,
    salaryCurrency: 'EUR',
    techStackTags: ['Python', 'SQL', 'scikit-learn', 'Airflow'],
    applyUrl: 'https://jobs.ashbyhq.com/traderepublic/1005/apply',
    postedAt: '2026-07-01T09:00:00.000Z',
    crawledAt: '2026-07-01T11:00:00.000Z',
    sourceTrustScore: 0.88,
    scamRiskScore: 0.07,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-06',
    sourceId: 'src-teamtailor-deutsche-bahn',
    sourceType: 'teamtailor',
    sourceUrl: 'https://career.deutschebahn.com/job/1006',
    originalJobId: 'db-1006',
    companyNameRaw: 'Deutsche Bahn AG',
    companyNameNormalized: 'Deutsche Bahn',
    jobTitleRaw: 'Junior Java-Entwickler (m/w/d)',
    jobTitleNormalized: 'Junior Java Developer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Entry-level role building internal logistics tools for rail operations. Java, Spring Boot, and SQL. Structured mentoring program for early-career engineers.',
    language: 'de',
    locationRaw: 'Frankfurt am Main, Deutschland',
    locationNormalized: 'Frankfurt am Main',
    countryCode: 'DE',
    remoteType: 'onsite',
    employmentType: 'full_time',
    seniority: 'junior',
    salaryMin: 48000,
    salaryMax: 58000,
    salaryCurrency: 'EUR',
    techStackTags: ['Java', 'Spring Boot', 'SQL'],
    applyUrl: 'https://career.deutschebahn.com/job/1006/apply',
    postedAt: '2026-06-25T09:00:00.000Z',
    crawledAt: '2026-06-26T08:00:00.000Z',
    sourceTrustScore: 0.82,
    scamRiskScore: 0.15,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-07',
    sourceId: 'src-greenhouse-hellofresh',
    sourceType: 'greenhouse',
    sourceUrl: 'https://boards.greenhouse.io/hellofresh/jobs/1007',
    originalJobId: 'hf-1007',
    companyNameRaw: 'HelloFresh SE',
    companyNameNormalized: 'HelloFresh',
    jobTitleRaw: 'React Native Developer',
    jobTitleNormalized: 'React Native Developer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Build features for our consumer mobile app used across 15 markets. React Native, TypeScript, and native module experience a plus.',
    language: 'en',
    locationRaw: 'Remote (Germany)',
    locationNormalized: 'Remote - Germany',
    countryCode: 'DE',
    remoteType: 'remote',
    employmentType: 'full_time',
    seniority: 'mid',
    salaryMin: 60000,
    salaryMax: 76000,
    salaryCurrency: 'EUR',
    techStackTags: ['React Native', 'TypeScript', 'React', 'Jest'],
    applyUrl: 'https://boards.greenhouse.io/hellofresh/jobs/1007/apply',
    postedAt: '2026-07-04T09:00:00.000Z',
    crawledAt: '2026-07-04T15:00:00.000Z',
    sourceTrustScore: 0.87,
    scamRiskScore: 0.1,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-08',
    sourceId: 'src-lever-deepl',
    sourceType: 'lever',
    sourceUrl: 'https://jobs.lever.co/deepl/1008',
    originalJobId: 'deepl-1008',
    companyNameRaw: 'DeepL SE',
    companyNameNormalized: 'DeepL',
    jobTitleRaw: 'Machine Learning Engineer',
    jobTitleNormalized: 'Machine Learning Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Improve neural machine translation models at scale. Strong Python and PyTorch background required, plus experience shipping ML systems to production.',
    language: 'en',
    locationRaw: 'Cologne, Germany',
    locationNormalized: 'Cologne',
    countryCode: 'DE',
    remoteType: 'hybrid',
    employmentType: 'full_time',
    seniority: 'senior',
    salaryMin: 80000,
    salaryMax: 100000,
    salaryCurrency: 'EUR',
    techStackTags: ['Python', 'PyTorch', 'Machine Learning', 'CUDA'],
    applyUrl: 'https://jobs.lever.co/deepl/1008/apply',
    postedAt: '2026-06-30T09:00:00.000Z',
    crawledAt: '2026-06-30T13:00:00.000Z',
    sourceTrustScore: 0.93,
    scamRiskScore: 0.05,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-09',
    sourceId: 'src-ashby-getyourguide',
    sourceType: 'ashby',
    sourceUrl: 'https://jobs.ashbyhq.com/getyourguide/1009',
    originalJobId: 'gyg-1009',
    companyNameRaw: 'GetYourGuide GmbH',
    companyNameNormalized: 'GetYourGuide',
    jobTitleRaw: 'Software Engineer, Backend (Go)',
    jobTitleNormalized: 'Backend Software Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Build high-throughput booking services for a global travel marketplace. Go, PostgreSQL, and event-driven architecture. Remote-friendly team spanning Europe.',
    language: 'en',
    locationRaw: 'Remote (Germany)',
    locationNormalized: 'Remote - Germany',
    countryCode: 'DE',
    remoteType: 'remote',
    employmentType: 'full_time',
    seniority: 'mid',
    salaryMin: 64000,
    salaryMax: 82000,
    salaryCurrency: 'EUR',
    techStackTags: ['Go', 'PostgreSQL', 'Kafka', 'Docker'],
    applyUrl: 'https://jobs.ashbyhq.com/getyourguide/1009/apply',
    postedAt: '2026-07-07T09:00:00.000Z',
    crawledAt: '2026-07-07T10:30:00.000Z',
    sourceTrustScore: 0.86,
    scamRiskScore: 0.09,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-10',
    sourceId: 'src-stepstone-quickcash',
    sourceType: 'stepstone',
    sourceUrl: 'https://www.stepstone.de/job/1010',
    originalJobId: 'qc-1010',
    companyNameRaw: 'QuickCash Global Consulting GmbH',
    companyNameNormalized: 'QuickCash Global Consulting',
    jobTitleRaw: 'URGENT! Home-Based Data Entry - No Experience - Start Today',
    jobTitleNormalized: 'Home-Based Data Entry',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Earn EUR 5,000+ per month working from home, no experience or interview required. Send a copy of your passport and a EUR 150 "training deposit" to secure your position. Contact only via WhatsApp.',
    language: 'en',
    locationRaw: 'Remote (worldwide)',
    locationNormalized: 'Remote',
    countryCode: 'DE',
    remoteType: 'remote',
    employmentType: 'part_time',
    seniority: null,
    salaryMin: 60000,
    salaryMax: 90000,
    salaryCurrency: 'EUR',
    techStackTags: [],
    applyUrl: 'https://www.stepstone.de/job/1010/apply',
    postedAt: '2026-07-08T09:00:00.000Z',
    crawledAt: '2026-07-08T09:15:00.000Z',
    sourceTrustScore: 0.28,
    scamRiskScore: 0.86,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-11',
    sourceId: 'src-greenhouse-personio',
    sourceType: 'greenhouse',
    sourceUrl: 'https://boards.greenhouse.io/personio/1011',
    originalJobId: 'personio-1011',
    companyNameRaw: 'Personio SE & Co. KG',
    companyNameNormalized: 'Personio',
    jobTitleRaw: 'Product Engineer (Python/React)',
    jobTitleNormalized: 'Product Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Ship end-to-end features across our HR SaaS platform. Python/Django backend, React frontend. High ownership, small cross-functional squads.',
    language: 'en',
    locationRaw: 'Munich, Germany',
    locationNormalized: 'Munich',
    countryCode: 'DE',
    remoteType: 'hybrid',
    employmentType: 'full_time',
    seniority: 'mid',
    salaryMin: 63000,
    salaryMax: 79000,
    salaryCurrency: 'EUR',
    techStackTags: ['Python', 'Django', 'React', 'TypeScript'],
    applyUrl: 'https://boards.greenhouse.io/personio/1011/apply',
    postedAt: '2026-07-03T09:00:00.000Z',
    crawledAt: '2026-07-03T14:00:00.000Z',
    sourceTrustScore: 0.9,
    scamRiskScore: 0.06,
    duplicateConfidence: 1,
  },
  {
    jobId: 'job-12',
    sourceId: 'src-lever-celonis',
    sourceType: 'lever',
    sourceUrl: 'https://jobs.lever.co/celonis/1012',
    originalJobId: 'celonis-1012',
    companyNameRaw: 'Celonis SE',
    companyNameNormalized: 'Celonis',
    jobTitleRaw: 'Working Student - Software Engineering',
    jobTitleNormalized: 'Working Student Software Engineer',
    jobDescriptionHtml: null,
    jobDescriptionText:
      'Support the platform team building process-mining infrastructure while completing your degree. Java or Python experience helpful. Flexible hours around your studies.',
    language: 'en',
    locationRaw: 'Munich, Germany',
    locationNormalized: 'Munich',
    countryCode: 'DE',
    remoteType: 'hybrid',
    employmentType: 'working_student',
    seniority: 'intern',
    salaryMin: 20000,
    salaryMax: 26000,
    salaryCurrency: 'EUR',
    techStackTags: ['Java', 'Python', 'SQL'],
    applyUrl: 'https://jobs.lever.co/celonis/1012/apply',
    postedAt: '2026-06-27T09:00:00.000Z',
    crawledAt: '2026-06-27T16:00:00.000Z',
    sourceTrustScore: 0.89,
    scamRiskScore: 0.06,
    duplicateConfidence: 1,
  },
];
