import { describe, expect, it } from 'vitest';
import pdfParse from 'pdf-parse';
import { buildApplicationPdf } from './application-pdf.js';

const candidate = { fullName: 'Jane Doe', email: 'jane@example.com' };

const job = {
  jobTitle: 'Backend Engineer',
  companyName: 'Acme GmbH',
  locationNormalized: 'Berlin',
  remoteType: 'hybrid',
  employmentType: 'full_time',
  salaryMin: 60000,
  salaryMax: 75000,
  salaryCurrency: 'EUR',
  applyUrl: 'https://boards.greenhouse.io/acme/jobs/1',
};

// Realistic lengths (roughly a ~380-word cover letter and a ~2-page CV), not a couple of
// sentences - short synthetic text hides pdfkit's automatic page-overflow path (see the
// reliability test below), which only triggers once a single `.text()` call's content
// doesn't fit on one page, exactly as real generated drafts don't.
const draft = {
  cvVariantText: 'Senior Backend Engineer with measurable delivery track record. '.repeat(60),
  coverLetterText: 'Dear Hiring Team, I am excited to apply for this role and believe my background is a strong fit. '.repeat(35),
  variantLabel: 'standard',
};

describe('buildApplicationPdf', () => {
  it('does not include the removed "Generated by" branding footer', async () => {
    const buffer = await buildApplicationPdf(candidate, job, draft);
    const { text } = await pdfParse(buffer);
    expect(text).not.toContain('German Smart Apply');
    expect(text).not.toMatch(/Generated \d{4}-\d{2}-\d{2}/);
  });

  it('renders the cover letter and CV on separate pages', async () => {
    const buffer = await buildApplicationPdf(candidate, job, draft);
    const { numpages, text } = await pdfParse(buffer);
    expect(numpages).toBeGreaterThanOrEqual(2);
    expect(text).toContain('Cover Letter');
    expect(text).toContain('Tailored CV (standard)');
  });

  // Regression guard for a pdfkit@0.19.x reentrancy bug (see the comment on
  // buildApplicationPdf): automatic page-overflow during a long `.text()` call can produce a
  // PDF with a corrupt xref table. Repeated runs with realistic-length content catch a
  // regression back to the naive `on('data')`/`on('end')` collection pattern, which hit this
  // close to 100% of the time for content this long.
  it('produces a structurally valid, parseable PDF across repeated runs with realistic-length content', async () => {
    for (let i = 0; i < 15; i += 1) {
      const buffer = await buildApplicationPdf(candidate, job, draft);
      await expect(pdfParse(buffer)).resolves.toBeTruthy();
    }
  });
});
